### ISSUE TITLE
Slate_Technologies “Meet Our Team” profile link not working

### ISSUE THREAD

**Issue by EarthRulerr** [joecooldoo/Hyposyn#2]
In the “Meet Our Team” section clicking on all profile images but Slate_Technologies brings them to a Snap! Profile, Slate_Technologies‘s image does nothing.

**Comment by joecooldoo** [comment]
This is a known issue, and should be fixed soon.

**Comment by joecooldoo** [comment]
https://github.com/joecooldoo/Hyposyn/commit/8737a7e77150180634455c57d27b2fd0836ca54c
